controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Company;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Product;
use app\models\ProductRealization;
use app\models\Role;
use app\models\SignupForm;
use app\models\Source;
use app\models\Unit;
use app\models\User;
use DateTime;
use yii\helpers\Url;

class PostController extends Controller
{

    public $errors = array();


    /**
     * Добавить новые данные
     */
    public function actionUpdateActual()
    {
        $lastProductRealization = ProductRealization::find()->orderBy(['release_date' => SORT_DESC])->one();



        $sources = Source::find()->all();
        $productsByFactories = array();


        $companies = Company::find()->all();

        foreach ($sources as $source) {
            $ip = $source->value;
            $url = "http://" . $ip . "";

            foreach ($companies as $key => $company) {
                $dt = new DateTime($lastProductRealization->release_date);
                $dt->modify('+1 day');
                $dtNow = new DateTime("now");

                while ($dt < $dtNow) {
                    $dateString = $dt->format("Y-m-d");
                    $id_company = $company->id_company;
                    // Получить информацию по конкретному предприятию (:factoryId) и список произведенной в (:timeKey) продукции.
                    $urlForFactoryDetail = $url . "/factories/" . $id_company . "/" . $dateString;
                    $factoriesDetailProducts = $this->getRestData($urlForFactoryDetail);

                    $isError = false;
                    if ($company->company_name != $factoriesDetailProducts['factoryCaption']) {
                        $isError = true;
                    }
                    if ($isError) {
                        $errorsDetail = array();
                        array_push($errorsDetail, "Нарушена целостность структуры данных");
                        array_push($errorsDetail, $company->id_company . " " . $company->company_name . " " . $company->entered);
                        array_push($errorsDetail, $factoriesDetailProducts['key'] . " " . $factoriesDetailProducts['factoryId'] . " " . $factoriesDetailProducts['factoryCaption']);
                        array_push($this->errors, $errorsDetail);
                        continue;
                    }


                    $this->updateProductRealization($factoriesDetailProducts['products'], $id_company, $dateString, $productsByFactories, true);
                    $dt->modify('+1 day');
                }
            }
        }

        $res = array();


        if (count($this->errors) > 0) {
            $res['status'] = "e";
            $res['data'] = "При обновление данных обнаружены ошибки";
        } else {

            $res['status'] = "s";
            $res['data'] = "Данные успешно обновлены";
        }


        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $this->asJson($res);
    }






    /**
     * Возвращает список предприятий
     */
    public function actionUpdateAll()
    {

        $units = array();


        ProductRealization::deleteAll();
        Company::deleteAll();
        Product::deleteAll();
        Unit::deleteAll();

        $sources = Source::find()->all();

        $factories = null;
        $productsByFactories = array();


        foreach ($sources as $source) {
            $ip = $source->value;
            $url = "http://" . $ip . "";
            // Получить более детализированную информацию по конкретному предприятию (:factoryId) и список выпускаемой им продукции
            $urlForFactories = $url . "/factories";
            $factories = $this->getRestData($urlForFactories);
            $this->updateCompanyFroDb($factories, 1);
            foreach ($factories as $factory) {
                $id_company = $factory['id'];
                //  Получить информацию по конкретному предприятию (:factoryId) и список произведенной в (:timeKey) продукции.
                $urlForFactoryDetail = $url . "/factories/" .  $id_company;
                $factoriesDetail = $this->getRestData($urlForFactoryDetail);
                array_push($productsByFactories, array($id_company => $factoriesDetail));
                $isError = false;
                if ($factory['caption'] != $factoriesDetail['caption']) {
                    $isError = true;
                }
                if ($factory['entered'] != $factoriesDetail['entered']) {
                    $isError = true;
                }
                if ($isError) {
                    $errorsDetail = array();
                    array_push($errorsDetail, "Нарушена целостность структуры данных");
                    array_push($errorsDetail, $factory['id'] . " " . $factory['caption'] . " " . $factory['entered']);
                    array_push($errorsDetail, $factoriesDetail['id'] . " " . $factoriesDetail['caption'] . " " . $factoriesDetail['entered']);
                    array_push($this->errors, $errorsDetail);
                    continue;
                }
                foreach ($factoriesDetail['products'] as $key => $value) {
                    $this->updateUnits($value['measure']);
                }
                $this->updateProductsForDb($factory['id'], $factoriesDetail['products']);
            }
            foreach ($factories as $key => $factory) {
                $dt = new DateTime("2020-01-01");
                $dtNow = new DateTime("now");
                while ($dt < $dtNow) {
                    $dateString = $dt->format("Y-m-d");
                    $id = $factory['id'];
                    // Получить информацию по конкретному предприятию (:factoryId) и список произведенной в (:timeKey) продукции.
                    $urlForFactoryDetail = $url . "/factories/" . $id . "/" . $dateString;
                    $factoriesDetailProducts = $this->getRestData($urlForFactoryDetail);
                    $id_company = $factory['id'];
                    $isError = false;
                    if ($factory['caption'] != $factoriesDetailProducts['factoryCaption']) {
                        $isError = true;
                    }
                    if ($isError) {
                        $errorsDetail = array();
                        array_push($errorsDetail, "Нарушена целостность структуры данных");
                        array_push($errorsDetail, $factory['id'] . " " . $factory['caption'] . " " . $factory['entered']);
                        array_push($errorsDetail, $factoriesDetailProducts['key'] . " " . $factoriesDetailProducts['factoryId'] . " " . $factoriesDetailProducts['factoryCaption']);
                        array_push($this->errors, $errorsDetail);
                        continue;
                    }
                    $this->updateProductRealization($factoriesDetailProducts['products'], $id_company, $dateString, $productsByFactories);
                    $dt->modify('+1 day');
                }
            }
        }

        $res = array();


        if (count($this->errors) > 0) {
            $res['status'] = "e";
            $res['data'] = "При обновление данных обнаружены ошибки";
        } else {

            $res['status'] = "s";
            $res['data'] = "Данные успешно обновлены";
        }


        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $this->asJson($res);
    }





    private function getRestData($url)
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_URL, $url);
        $result = curl_exec($ch);
        curl_close($ch);
        return json_decode($result, true);
    }



    private function updateUnits($value)
    {
        $unit = Unit::findOne(["measure" => $value]);
        if ($unit == null) {
            $unit = new Unit();
            $unit->measure = $value;
            $unit->save();
        }
    }

    private function updateCompanyFroDb($factories, $id_division = 1)
    {
        foreach ($factories as $factory) {
            $company = new Company();
            $company->id_company = $factory['id'];
            $company->company_name = $factory['caption'];
            $company->entered = $factory['entered'];
            $company->id_division = $id_division;
            $company->save();
        }
    }

    private function updateProductsForDb($id_company, $data_products)
    {
        foreach ($data_products as $value) {
            $product = new Product();
            $product->id_product = $id_company . $value['id'];
            $product->articul = $value['articul'];
            $product->caption = $value['caption'];
            $product->save();
        }
    }

    private function updateProductRealization($data_products, $id_company, $release_date, $productsByFactories, $isCreateProduct = false)
    {
        foreach ($data_products as $value) {
            $productRealization = new ProductRealization();
            $productRealization->quantity = $value['qty'];
            $productRealization->id_company = $id_company;
            $productRealization->release_date = $release_date;
            if ($isCreateProduct) {
                $product = Product::find()->where(['id_product' => $id_company . $value['id']])->one();
                if ($product == null) {
                    $product = new Product();
                    $product->id_product = $id_company . $value['id'];
                    $product->articul = $value['articul'];
                    $product->caption = $value['caption'];
                    $product->save();
                }
            } else {
                $productRealization->id_product = $id_company . $value['id'];
            }


            $isBreak = false;
            $priceValue = 0;
            foreach ($productsByFactories as $productByFactories) {
                if ($isBreak) {

views/layouts/main-noauth.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body>
    <?php $this->beginBody() ?>

    <div class="wrap">

        <nav id="w0" class="navbar-inverse navbar-fixed-top navbar">
            <div class="container">
                <div class="navbar-header d-flex flex-row">
                    <a class="navbar-brand" href="/app/web/index.php">Система производственных отчетов</a>



                </div>
            </div>
        </nav>
        <div class="container">
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <p>FOOTER</p>
        </div>
    </footer>
    <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\User;
use yii\helpers\Url;

AppAsset::register($this);


$userActive = User::findOne(['id_user' => Yii::$app->user->id]);


?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body>
    <?php $this->beginBody() ?>

    <div class="wrap">
        <div class="container">
            <?= Alert::widget() ?>

            <div class="row">
                <div class="col-3">
                    <div class="">
                        <div class="d-flex flex-column block-name">
                            <?php


                            ?>
                            <p class="h-sup"><?= $userActive->last_name ?></p>
                            <p class="h-sup"><?= $userActive->first_name ?></p>
                            <p class="h-sup"><?= $userActive->second_name ?></p>
                        </div>
                        <hr>
                        <div class="d-flex flex-column block-role">
                            <?php if ($userActive->admin) : ?>
                                <p>Администратор</p>
                            <?php else : ?>
                                <p>Топ-менеджер </p>
                            <?php endif ?>
                            <a href="<?= Url::toRoute(['/site/logout']) ?>" class="btn btn-primary mt-2 mb-1" type="button">Выйти</a>
                            <a href="<?= Url::home() ?>" class="btn btn-primary" type="button">Главная</a>

                        </div>
                        <hr>
                    </div>
                    <div class="d-grid gap-2">
                        <?php if ($userActive->admin) : ?>
                            <a href="<?= Url::toRoute(['/source/']) ?>" class="btn btn-primary" type="button">Управление источниками</a>
                            <a href="<?= Url::toRoute(['/user/']) ?>" class="btn btn-primary" type="button">Управление пользователями</a>
                            <button id="ButtonUpdateAll" data-action="<?= Url::toRoute(['post/update-all']) ?>" class="btn btn-success">Обновить все данные</button>
                        <?php else : ?>
                            <a href="<?= Url::toRoute(['order/price-for-year']) ?>" class="btn btn-primary" type="button">Просмотреть стоимостные характеристики продукции за год</a>
                            <a href="<?= Url::toRoute(['order/realization-period']) ?>" class="btn btn-primary" type="button">Просмотр произведенной продукции за период</a>
                            <a href="<?= Url::toRoute(['order/compare-for-year']) ?>" class="btn btn-primary" type="button">Сравнить показатели предыдущего периода</a>
                        <?php endif ?>
                        <button id="ButtonUpdate" data-action="<?= Url::toRoute(['post/update-actual']) ?>" href="<?= Url::toRoute(['post/update-actual']) ?>" class="btn btn-primary" type="button">Обновить данные</button>
                    </div>

                </div>

                <div class="col-9">
                    <?= $content ?>
                </div>


            </div>





        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <p id="Msg"></p>
        </div>
    </footer>
    <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>